version: "3"
services:
  momentum-active-points-app:
    container_name: momentum-active-points-app
    build:
      context: ./
      dockerfile: Dockerfile
    image: momentum-active-points-app
    depends_on:
       - prometheus
    ports:
        - "8081:8081"
    hostname: momentum-active-points-app
    networks:
      - momentum-network
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    hostname: prometheus
    networks:
      - momentum-network
networks:
  momentum-network:
    driver: bridge
