INSERT INTO CUSTOMER VALUES(1,'Nivea Lotion',25);
INSERT INTO CUSTOMER VALUES(2,'Nivea Roll On',10);
INSERT INTO CUSTOMER VALUES(3,'Dishwashing Liquid',25);
INSERT INTO CUSTOMER VALUES(5,'Tyhobeka',10);
INSERT INTO CUSTOMER VALUES(6,'Mkhuseli',25);
INSERT INTO CUSTOMER VALUES(7,'Tyhobeka',10);

INSERT INTO PRODUCT VALUES(1,5,1);
INSERT INTO PRODUCT VALUES(2,6,1);
INSERT INTO PRODUCT VALUES(3,6,2);
